######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 4 18:00:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
